{% set name = "anaconda-client" %}
{% set version = "1.6.3" %}
{% set checksum = "86a61c88dfb400b93fa2211f51d89492b21218207e3c9b4f816ff7179f7958cd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Anaconda-Platform/anaconda-client/archive/{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - anaconda = binstar_client.scripts.cli:main
    - binstar = binstar_client.scripts.cli:main
    - conda-server = binstar_client.scripts.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - clyent
    - requests >=2.9.1
    - pyyaml
    - python-dateutil
    - pytz

test:
  imports:
    - binstar_client
    - binstar_client.commands
    - binstar_client.inspect_package
    - binstar_client.inspect_package.tests
    - binstar_client.mixins
    - binstar_client.scripts
    - binstar_client.tests
    - binstar_client.utils
    - binstar_client.utils.notebook
    - binstar_client.utils.notebook.tests

  commands:
    - anaconda --help
    - binstar --help
    - conda-server --help

about:
  home: https://github.com/Anaconda-Platform/anaconda-client
  license: BSD 3-Clause
  license_file: LICENSE.md
  summary: Anaconda Cloud command line client library

extra:
  recipe-maintainers:
    - jakirkham
